language: c

sudo: true

addons:
  apt_packages:
    - pandoc

script: 
  - cd RBigObject && ./../travis-tool.sh run_tests && cd ..

after_failure:
  - ./travis-tool.sh dump_logs

before_install:
  - docker pull macrodata/bigobject-community
  - docker run -t -d --name bigobject -p 9090:9090 macrodata/bigobject-community
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - cd RBigObject && ./../travis-tool.sh install_deps && cd ..
  # Install testthat after running install_deps, otherwise devtools itself might be installed from CRAN or c2d4u

after_success:
notifications:
  email:
    on_success: change
    on_failure: change
env:
  - global:
    - WARNINGS_ARE_ERRORS=1
    - _R_CHECK_FORCE_SUGGESTS_=0
    - BOOTSTRAP_LATEX=1
    - R_BUILD_ARGS=--no-manual
    - R_CHECK_ARGS=--no-manual
    - BIGOBJECT_IP=127.0.0.1
    - BIGOBJECT_PORT=9090

services:
  - docker
